// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// source: determined/api/v1/slots_filter.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Filter workloads by the slot count they request: experiments by
// resources.slots_per_trial (1 when the config leaves it out, its default),
// generic tasks by the resources.slots stored with the task (0 when the stored
// config has none, as the task's slots field reports it). The filter counts
// slots of any type. A slot is a GPU only in a resource pool whose slot type
// is cuda or rocm; in a pool whose slot type is cpu, a slot is a CPU, so a
// workload with slots does not necessarily use a GPU.
type SlotsFilter int32

const (
	// No filter.
	SlotsFilter_SLOTS_FILTER_UNSPECIFIED SlotsFilter = 0
	// Workloads that request at least one slot.
	SlotsFilter_SLOTS_FILTER_HAS_SLOTS SlotsFilter = 1
	// Workloads that request no slots: a slot count of 0.
	SlotsFilter_SLOTS_FILTER_ZERO_SLOTS SlotsFilter = 2
)

// Enum value maps for SlotsFilter.
var (
	SlotsFilter_name = map[int32]string{
		0: "SLOTS_FILTER_UNSPECIFIED",
		1: "SLOTS_FILTER_HAS_SLOTS",
		2: "SLOTS_FILTER_ZERO_SLOTS",
	}
	SlotsFilter_value = map[string]int32{
		"SLOTS_FILTER_UNSPECIFIED": 0,
		"SLOTS_FILTER_HAS_SLOTS":   1,
		"SLOTS_FILTER_ZERO_SLOTS":  2,
	}
)

func (x SlotsFilter) Enum() *SlotsFilter {
	p := new(SlotsFilter)
	*p = x
	return p
}

func (x SlotsFilter) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SlotsFilter) Descriptor() protoreflect.EnumDescriptor {
	return file_determined_api_v1_slots_filter_proto_enumTypes[0].Descriptor()
}

func (SlotsFilter) Type() protoreflect.EnumType {
	return &file_determined_api_v1_slots_filter_proto_enumTypes[0]
}

func (x SlotsFilter) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SlotsFilter.Descriptor instead.
func (SlotsFilter) EnumDescriptor() ([]byte, []int) {
	return file_determined_api_v1_slots_filter_proto_rawDescGZIP(), []int{0}
}

var File_determined_api_v1_slots_filter_proto protoreflect.FileDescriptor

var file_determined_api_v1_slots_filter_proto_rawDesc = []byte{
	0x0a, 0x24, 0x64, 0x65, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x65, 0x64, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x76, 0x31, 0x2f, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x64, 0x65, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e,
	0x65, 0x64, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2a, 0x64, 0x0a, 0x0b, 0x53, 0x6c, 0x6f,
	0x74, 0x73, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x18, 0x53, 0x4c, 0x4f, 0x54,
	0x53, 0x5f, 0x46, 0x49, 0x4c, 0x54, 0x45, 0x52, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1a, 0x0a, 0x16, 0x53, 0x4c, 0x4f, 0x54, 0x53, 0x5f,
	0x46, 0x49, 0x4c, 0x54, 0x45, 0x52, 0x5f, 0x48, 0x41, 0x53, 0x5f, 0x53, 0x4c, 0x4f, 0x54, 0x53,
	0x10, 0x01, 0x12, 0x1b, 0x0a, 0x17, 0x53, 0x4c, 0x4f, 0x54, 0x53, 0x5f, 0x46, 0x49, 0x4c, 0x54,
	0x45, 0x52, 0x5f, 0x5a, 0x45, 0x52, 0x4f, 0x5f, 0x53, 0x4c, 0x4f, 0x54, 0x53, 0x10, 0x02, 0x42,
	0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x65,
	0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x65, 0x64, 0x2d, 0x61, 0x69, 0x2f, 0x64, 0x65, 0x74, 0x65,
	0x72, 0x6d, 0x69, 0x6e, 0x65, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x61, 0x70, 0x69, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_determined_api_v1_slots_filter_proto_rawDescOnce sync.Once
	file_determined_api_v1_slots_filter_proto_rawDescData = file_determined_api_v1_slots_filter_proto_rawDesc
)

func file_determined_api_v1_slots_filter_proto_rawDescGZIP() []byte {
	file_determined_api_v1_slots_filter_proto_rawDescOnce.Do(func() {
		file_determined_api_v1_slots_filter_proto_rawDescData = protoimpl.X.CompressGZIP(file_determined_api_v1_slots_filter_proto_rawDescData)
	})
	return file_determined_api_v1_slots_filter_proto_rawDescData
}

var file_determined_api_v1_slots_filter_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_determined_api_v1_slots_filter_proto_goTypes = []interface{}{
	(SlotsFilter)(0), // 0: determined.api.v1.SlotsFilter
}
var file_determined_api_v1_slots_filter_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_determined_api_v1_slots_filter_proto_init() }
func file_determined_api_v1_slots_filter_proto_init() {
	if File_determined_api_v1_slots_filter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_determined_api_v1_slots_filter_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_determined_api_v1_slots_filter_proto_goTypes,
		DependencyIndexes: file_determined_api_v1_slots_filter_proto_depIdxs,
		EnumInfos:         file_determined_api_v1_slots_filter_proto_enumTypes,
	}.Build()
	File_determined_api_v1_slots_filter_proto = out.File
	file_determined_api_v1_slots_filter_proto_rawDesc = nil
	file_determined_api_v1_slots_filter_proto_goTypes = nil
	file_determined_api_v1_slots_filter_proto_depIdxs = nil
}
